// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Navbar from "@/components/Navbar";
import { AppProvider } from "@/context/AppContext";
import { Playfair_Display } from "next/font/google";

export const metadata = {
  title: "Fashion Brand",
  description: "Premium fashion brand",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        {/* 🔑 GLOBAL STATE WRAPPER */}
        <AppProvider>
          <Navbar />

          {/* Offset for fixed navbar */}
          <main className="pt-24">
            {children}
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
