# Generated by Django 5.2.9 on 2026-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COLOR_MISMATCH", "Color mismatch"),
                    ("WRONG_SIZE", "Wrong size"),
                    ("ADDRESS_CHANGE", "Address change"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
