# Generated by Django 5.2.9 on 2026-01-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
    ]
