# Generated by Django 5.2.9 on 2025-12-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
